=== mdijkstra/molgenis/molgenis-model-registry/src/test/resources/PhenDB/PhenDB.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="gscf" xmlns="gscf" elementFormDefault="qualified">
	<xs:element name="templates">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="template" minOccurs="0" maxOccurs="unbounded" type="templateType" />
			</xs:sequence>
			<xs:attribute name="count" type="xs:integer" />
		</xs:complexType>
	</xs:element>

	<xs:complexType name="templateType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="description" type="xs:string"/>
			<xs:element name="entity" type="xs:string"/>

			<xs:element name="templateFields"> 
				<xs:complexType>
					<xs:sequence>
						<xs:element name="templateField" minOccurs="0" maxOccurs="unbounded" type="templateFieldType" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="templateFieldType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="type" type="xs:string"/>
			<xs:element name="unit" type="xs:string"/>
			<xs:element name="comment" type="xs:string"/>
			<xs:element name="required" type="xs:boolean" minOccurs="0" />
			<xs:element name="preferredIdentifier" type="xs:boolean" minOccurs="0" />

			<xs:element name="ontologies" minOccurs="0"> 
				<xs:complexType>
					<xs:sequence>
						<xs:element name="ontology" minOccurs="0" maxOccurs="unbounded" type="ontologyType" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<xs:element name="listItems" minOccurs="0"> 
				<xs:complexType>
					<xs:sequence>
						<xs:element name="listItem" minOccurs="0" maxOccurs="unbounded" type="listItemType" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ontologyType">
		<xs:sequence>
			<xs:element name="ncboId" type="xs:integer"/>
			<xs:element name="ncboVersionedId" type="xs:integer"/>
			<xs:element name="name" type="xs:string" minOccurs="0" />
			<xs:element name="description" type="xs:string" minOccurs="0" />
			<xs:element name="url" type="xs:string" minOccurs="0" />
			<xs:element name="versionNumber" type="xs:string" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="listItemType">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== mdijkstra/molgenis/molgenis-model-registry/src/test/resources/PhenDB/PhenDB_NMC/PhenDB_NMC.xml
<?xml version="1.0"?>
<templates xmlns="gscf" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="gscf ../PhenDB.xsd" count="9">
  
	<template>
		<name>qRT-PCR SYBR Green</name>
		<description>Contains information on measured variables and experimental metadata.</description>
		<entity>org.dbxp.sam.Feature</entity>

		<templateFields>
		  
			<templateField>
				<name>Version</name>
				<type>STRING</type>
				<unit></unit>
				<comment></comment>
				<required>false</required>
				<preferredIdentifier>false</preferredIdentifier>

				
				
			</templateField>
		  
			<templateField>
				<name>Gene Full-Name(s)</name>
				<type>STRING</type>
				<unit></unit>
				<comment>Full name(s) of the target gene, e.g. NCBI definition.</comment>
				<required>false</required>
				<preferredIdentifier>false</preferredIdentifier>

				
				
			</templateField>
		  
			<templateField>
				<name>Target Gene Symbol (HGNC)</name>
				<type>STRING</type>
				<unit></unit>
				<comment>Name of the target gene using HGNC term (for human subjects)</comment>
				<required>false</required>
				<preferredIdentifier>false</preferredIdentifier>

				
				
			</templateField>
		  
			<templateField>
				<name>Gene Ontology</name>
				<type>STRING</type>
				<unit></unit>
				<comment>NCBI code
GI code
For the gene of interest</comment>
				<required>false</required>
				<preferredIdentifier>false</preferredIdentifier>

				
				
			</templateField>
		  
			<templateField>
				<name>Gene_Forward primer</name>
				<type>STRING</type>
				<unit></unit>
				<comment>Forward primer; orientation given as standard: 5&apos;-3&apos; (nt)


</comment>
				<required>false</required>
				<preferredIdentifier>false</preferredIdentifier>

				
				
			</templateField>
		  
			<templateField>
				<name>Gene_Reverse primer</name>
				<type>STRING</type>
				<unit></unit>
				<comment>Reverse primer: orientation given as standard: 5&apos;-3&apos; (nt)</comment>
				<required>false</required>
				<preferredIdentifier>false</preferredIdentifier>

				
				
			</templateField>
		  
			<templateField>
				<name>Annealing temperature (Tm)_Target Gene primers</name>
				<type>DOUBLE</type>
				<unit>&#176;Celsius</unit>
				<comment>Annealing temperature of the primer pair for the gene of interest.</comment>
				<required>false</required>
				<preferredIdentifier>false</preferredIdentifier>

				
				
			</templateField>
		  
			<templateField>
				<name>Reference Gene Full-Name(s)</name>
				<type>STRING</type>
				<unit></unit>
				<comment>Full name(s) of the reference (housekeeping or control) gene, e.g. NCBI definition.</comment>
				<required>false</required>
				<preferredIdentifier>false</preferredIdentifier>

				
				
			</templateField>
		  
			<templateField>
				<name>Reference Gene Symbol (HGNC)</name>
				<type>STRING</type>
				<unit></unit>
				<comment>Name of the reference (housekeeping or control) gene, using HGNC term (for human subjects).</comment>
				<required>false</required>
				<preferredIdentifier>false</preferredIdentifier>

				
				
			</templateField>
		  
			<templateField>
				<name>Reference Gene Ontology</name>
				<type>STRING</type>
				<unit></unit>
				<comment>NCBI code
GI code
For the reference (housekeeping or control) gene.</comment>
				<required>false</required>
				<preferredIdentifier>false</preferredIdentifier>

				
				
			</templateField>
		  
			<templateField>
				<name>Reference Gene_Forward primer</name>
				<type>STRING</type>
				<unit></unit>
				<comment>Orientation given as standard: 5&apos;-3&apos;
</comment>
				<required>false</required>
				<preferredIdentifier>false</preferredIdentifier>

				
				
			</templateField>
		  
			<templateField>
				<name>Reference Gene_Reverse primer</name>
				<type>STRING</type>
				<unit></unit>
				<comment>Orientation given as standard: 5&apos;-3&apos;</comment>
				<required>false</required>
				<preferredIdentifier>false</preferredIdentifier>

				
				
			</templateField>
		  
			<templateField>
				<name>Annealing temperature (Tm)_Reference Gene primers</name>
				<type>DOUBLE</type>
				<unit>&#176;Celsius</unit>
				<comment>Annealing temperature of the primer pair for the reference gene.</comment>
				<required>false</required>
				<preferredIdentifier>false</preferredIdentifier>

				
				
			</templateField>
		  
			<templateField>
				<name>Description</name>
				<type>TEXT</type>
				<unit></unit>
				<comment>Description on how the qRT-PCR was performed. 
(can be reference to a published article or an online site with the protocol)</comment>
				<required>false</required>
				<preferredIdentifier>false</preferredIdentifier>

				
				
			</templateField>
		  
			<templateField>
				<name>Machine used for qRT-PCR (manufacturer)</name>
				<type>STRING</type>
				<unit></unit>
				<comment>Description on what type of machine the experiment was performed.</comment>
				<required>false</required>
				<preferredIdentifier>false</preferredIdentifier>

				
				
			</templateField>
		  
			<templateField>
				<name>Reporter dye (manufacturer)</name>
				<type>STRING</type>
				<unit></unit>
				<comment></comment>
				<required>false</required>
				<preferredIdentifier>false</preferredIdentifier>

				
				
			</templateField>
		  
			<templateField>
				<name>Software used for analysis of qRT-PCR results</name>
				<type>STRING</type>
				<unit></unit>
				<comment>Name of software (+version) used for analysis of qRT-PCR.</comment>
				<required>false</required>
				<preferredIdentifier>false</preferredIdentifier>

				
				
			</templateField>
		  
			<templateField>
				<name>Experimental protocol</name>
				<type>FILE</type>
				<unit></unit>
				<comment>Experimental protocol describing how detection for methylation of the gene of interest was performed.</comment>
				<required>false</required>
				<preferredIdentifier>false</preferredIdentifier>

				
				
			</templateField>
		  
			<templateField>
				<name>Analysis/calculation unit value of the measured feature</name>
				<type>TEXT</type>
				<unit></unit>
				<comment>Calculation/formula for obtaining processed data measurements (e.g. for a target gene compared to reference gene)</comment>
				<required>false</required>
				<preferredIdentifier>false</preferredIdentifier>

				
				
			</templateField>
		  
			<templateField>
				<name>Target gene primer manufacturer</name>
				<type>STRING</type>
				<unit></unit>
				<comment></comment>
				<required>false</required>
				<preferredIdentifier>false</preferredIdentifier>

				
				
			</templateField>
		  
			<templateField>
				<name>Reference gene primer manufacturer</name>
				<type>STRING</type>
				<unit></unit>
				<comment></comment>
				<required>false</required>
				<preferredIdentifier>false</preferredIdentifier>

				
				
			</templateField>
		  
			<templateField>
				<name>Additional information</name>
				<type>TEXT</type>
				<unit></unit>
				<comment>E.g. information on DNA isolation and bisulphite modification could be referred to here.
In case primers and probes are from a published article, could refer to article here as well.</comment>
				<required>false</required>
				<preferredIdentifier>false</preferredIdentifier>

				
				
			</templateField>
		  
		</templateFields>
	</template>
  
	<template>
		<name>MLPA gain P146-A1</name>
		<description>Features for the MLPA kit, gain P146-A1 from MRC Holland.</description>
		<entity>org.dbxp.sam.Feature</entity>

		<templateFields>
		  
			<templateField>
				<name>Chromosomal position</name>
				<type>STRING</type>
				<unit></unit>
				<comment>Chromosomal position of the probes in the kit.</comment>
				<required>false</required>
				<preferredIdentifier>false</preferredIdentifier>

				
				
			</templateField>
		  
			<templateField>
				<name>Gene (kit name)</name>
				<type>STRING</type>
				<unit></unit>
				<comment>Gene name as supplied by the MLPA kit.</comment>
				<required>false</required>
				<preferredIdentifier>false</preferredIdentifier>

				
				
			</templateField>
		  
			<templateField>
				<name>Length</name>
				<type>LONG</type>
				<unit>basepairs (bp)</unit>
				<comment></comment>
				<required>false</required>
				<preferredIdentifier>false</preferredIdentifier>

				
				
			</templateField>
		  
			<templateField>
				<name>MV36</name>
				<type>STRING</type>
				<unit></unit>
				<comment></comment>
				<required>false</required>
				<preferredIdentifier>false</preferredIdentifier>

				
				
			</templateField>
		  
			<templateField>
				<name>Recommended order</name>
				<type>LONG</type>
				<unit></unit>
				<comment>Recommended order as suggested by the MLPA kit supplier.</comment>
				<required>false</required>
				<preferredIdentifier>false</preferredIdentifier>

				
				
			</templateField>
		  
			<templateField>
				<name>Product company</name>
				<type>STRING</type>
				<unit></unit>
				<comment></comment>
				<required>false</required>
				<preferredIdentifier>false</preferredIdentifier>

				
				
			</templateField>
		  
			<templateField>
				<name>Product information</name>
				<type>STRING</type>
				<unit></unit>
				<comment></comment>
				<required>false</required>
				<preferredIdentifier>false</preferredIdentifier>

				
				
			</templateField>
		  
			<templateField>
				<name>Product information_Lot# kit</name>
				<type>STRING</type>
				<unit></unit>
				<comment>Lot# of the product used for the experiments</comment>
				<required>false</required>
				<preferredIdentifier>false</preferredIdentifier>

				
				
			</templateField>
		  
			<templateField>
				<name>Normalisation method</name>
				<type>STRINGLIST</type>
				<unit></unit>
				<comment>Normalisation method applied to MLPA data (tumor or population analysis)</comment>
				<required>false</required>
				<preferredIdentifier>false</preferredIdentifier>

				
				
				  <listItems>
					
					  <listItem>
